name: Deploy static content to Pages

on:
  # Запускать скрипт при пуше в ветку main
  push:
    branches: ["main"]
  # Позволяет запускать скрипт вручную из интерфейса GitHub Actions
  workflow_dispatch:

# Устанавливаем необходимые права для деплоя на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Настраиваем очереди, чтобы новые деплои не конфликтовали со старыми
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Загружаем папку dist (результат сборки Vite)
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
